name: autofix.ci
on:
  pull_request:
  push:
    branches: ['main']
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: poetry

      - working-directory: tests/ocpp-server
        run: |
          poetry install --no-root
          poetry run task format

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - run: pnpm install --ignore-scripts

      - run: pnpm format

      - working-directory: ui/web
        run: |
          pnpm format
          pnpm lint:fix

      - uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
